#!/bin/bash

norminette

SOURCE_FILES=(
    "ex00/ft_strcmp.c"
    "ex01/ft_strncmp.c"
    "ex02/ft_strcat.c"
    "ex03/ft_strncat.c"
    "ex04/ft_strstr.c"
    "ex05/ft_strlcat.c"
    "main.c"
)
# Compile each source file if it exists
for file in "${SOURCE_FILES[@]}"; do
    if [ -e "$file" ]; then
        cc -c "$file"
    else
        echo "File $file does not exist."
    fi
done

# Link all object files into the executable
cc -o C02_Tests *.o -Wall -Wextra -Werror -Wsign-compare -Wuninitialized

# Clean up object files
rm -f *.o
