#!/bin/bash

norminette

SOURCE_FILES=("ex00/ft_ft.c" "ex01/ft_ultimate_ft.c" "ex02/ft_swap.c" "ex03/ft_div_mod.c" "ex04/ft_ultimate_div_mod.c" "ex05/ft_putstr.c" "ex06/ft_strlen.c" "ex07/ft_rev_int_tab.c" "main.c")
# Compile each source file if it exists
for file in "${SOURCE_FILES[@]}"; do
    if [ -e "$file" ]; then
        cc -c "$file"
    else
        echo "File $file does not exist."
    fi
done

# Link all object files into the executable
cc -o C01_Tests *.o

# Clean up object files
rm -f *.o
